name: Grading

on:
  pull_request:
    branches: [ main ]

jobs:
  grading-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container:
      image: vladimirkutuev/cmocka:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 2
          token: ${{ secrets.GH_DB_TOKEN }}
      - name: Configure git repository
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Show submodule updated
        run: git diff --name-only HEAD^
      - name: Show submodule updated
        run: ./3-grading-tests/scripts/check_clean.sh
      - name: Test
        run: ./3-grading-tests/scripts/test.sh
